<?php

/**
 * PluginTSchedScheduleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTSchedScheduleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTSchedScheduleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTSchedSchedule');
    }
}