<?php

/**
 * PluginTSchedTaskOptionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTSchedTaskOptionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTSchedTaskOptionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTSchedTaskOption');
    }
}