<?php

/**
 * PluginTSchedLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTSchedLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTSchedLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTSchedLog');
    }
}