<?php

/**
 * PluginTSchedQueueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTSchedQueueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTSchedQueueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTSchedQueue');
    }
}