<?php

/**
 * PluginTSchedTaskArgumentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTSchedTaskArgumentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTSchedTaskArgumentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTSchedTaskArgument');
    }
}