<?php

/**
 * PluginTSchedTaskTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTSchedTaskTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTSchedTaskTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTSchedTask');
    }
}