options:
  type: InnoDB
TSchedTask:
  connection: doctrine
  tableName: tsched_task
  actAs: { Timestampable: ~ }
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    brief_description:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    detailed_description:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    class_name:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
TSchedTaskArgument:
  connection: doctrine
  tableName: tsched_task_argument
  actAs: { Timestampable: ~ }
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    tsched_task_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      autoincrement: false
    name:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    value:
      type: string(500)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    TSchedTask:
      local: tsched_task_id
      foreign: id
TSchedTaskOption:
  connection: doctrine
  tableName: tsched_task_option
  actAs: { Timestampable: ~ }
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    tsched_task_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      autoincrement: false
    name:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    value:
      type: string(500)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    TSchedTask:
      local: tsched_task_id
      foreign: id
TSchedSchedule:
  connection: doctrine
  tableName: tsched_schedule
  actAs: { Timestampable: ~ }
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    task_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    minute:
      type: string(3)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    hour:
      type: string(3)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    dayofweek:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    enabled:
      type: boolean
  relations:
    TSchedTask:
      local: task_id
      foreign: id
TSchedLog:
  connection: doctrine
  tableName: tsched_log
  actAs: { Timestampable: ~ }
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    schedule_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    start:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    end:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    outcome:
      type: boolean
    output:
      type: string(500)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    TSchedSchedule:
      local: schedule_id
      foreign: id
TSchedQueue:
  connection: doctrine
  tableName: tsched_queue
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    schedule_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
  relations:
    TSchedSchedule:
      local: schedule_id
      foreign: id
